hydra:
  searchpath:
    - file://../../verl/trainer/config

defaults:
  - sft_trainer
  - _self_

data:
  train_files: /home/ubuntu/data/gsm8k/train.parquet
  val_files: /home/ubuntu/data/gsm8k/test.parquet
  train_batch_size: 512
  micro_batch_size_per_gpu: 16
  max_length: 2048
  prompt_key: extra_info
  prompt_dict_keys: ['question']
  response_key: extra_info
  response_dict_keys: ['answer']

model:
  partial_pretrain: /home/ubuntu/model/Qwen2.5-0.5B
  enable_gradient_checkpointing: true
  fsdp_config:
    model_dtype: bfloat16
  strategy: fsdp2

optim:
  lr: 1.0e-5
  lr_warmup_steps_ratio: 0.1

ulysses_sequence_parallel_size: 2
use_remove_padding: true

trainer:
  n_gpus_per_node: 8
  nnodes: 1
  total_epochs: 15
  resume_mode: disable
  logger: ["console", "wandb"]
  project_name: numina-cot
  experiment_name: sft
  default_local_dir: /home/ubuntu/repos/verl/examples/sft/checkpoints/qwen2.5-math-0.5b
  save_freq: 10
  test_freq: 10

